# Generated by Django 4.0.1 on 2022-02-21 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_departments_ratings_remove_person_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Review',
        ),
    ]
